import { Box } from '../Box/Box';
import { StyledMainContainer } from './MainContainer.styled';

import Head from 'next/head';

type Props = {
  children?: JSX.Element;
};

export const MainContainer = ({ children }: Props) => {
  return (
    <StyledMainContainer>
      <Head>
        <title>FS Next</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box p={40} width="100%" minWidth={550}>
        {children}
      </Box>
    </StyledMainContainer>
  );
};
