import { Box } from './Box/Box';
import { StyledMainContainer } from './MainContainer.styled';
import img from '../../images/tileable-doodle.png';

import Head from 'next/head';
import { ReactComponentElement } from 'react';

type Props = {
  children?: JSX.Element;
};

export const MainContainer = ({ children }: Props) => {
  return (
    <StyledMainContainer>
      <Head>
        <title>React-FS </title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>{children}</Box>
    </StyledMainContainer>
  );
};
